// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdnpareharddegunrjyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkbnBhcmVoYXJkZGVndW5yanl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NDA5NTIsImV4cCI6MjA3NDQxNjk1Mn0.l3704FE9ehkCKxMvUeT1BWrsX_S6iLooB_nj8rHbn4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});